### POST request to create patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Kafka bro",
  "email": "kafka-test6@gmail.com",
  "address": "India",
  "dateOfBirth": "1992-09-09",
  "registeredDate": "2024-11-28"
}

###